import { PHI } from './core.js';
import {
  filletPoints,
  makeEdgeShape,
  makeRadialShape,
  makeRepeatingEdgeShape,
  makeRepeatingRadialShape,
  makeSuperellipseShape,
} from './builders.js';

function normalizeSafeInset(value) {
  if (typeof value === 'number') {
    return { top: value, right: value, bottom: value, left: value };
  }

  return value;
}

function createDefinition(defaults, metadata, points) {
  const { selection = {}, ...rest } = metadata;
  return {
    ...defaults,
    ...rest,
    selection: {
      ...defaults.selection,
      ...selection,
      aspect: {
        ...defaults.selection.aspect,
        ...selection.aspect,
      },
      safeInset: normalizeSafeInset(selection.safeInset ?? metadata.safeInset),
    },
    points,
  };
}

const edge = (metadata, geometry) => createDefinition({
  family: 'frame',
  precision: 3,
  tension: 0,
  selection: {
    uses: ['card', 'panel'],
    aspect: { min: 1, preferred: 1.5, max: 2.5 },
    contentCapacity: 'dense',
    symmetry: 'none',
    balance: 'centered',
    edgeActivity: 'moderate',
  },
}, metadata, makeEdgeShape(geometry));

const repeatEdge = (metadata, geometry) => createDefinition({
  family: 'scalloped',
  precision: 3,
  tension: 0,
  selection: {
    uses: ['card', 'panel'],
    aspect: { min: 1, preferred: 1.5, max: 2.5 },
    contentCapacity: 'standard',
    symmetry: 'bilateral',
    balance: 'centered',
    edgeActivity: 'active',
  },
}, metadata, makeRepeatingEdgeShape(geometry));

const radial = (metadata, geometry) => createDefinition({
  family: 'blob',
  precision: 3,
  tension: 0,
  selection: {
    uses: ['badge', 'media'],
    aspect: { min: 0.8, preferred: 1, max: 1.25 },
    contentCapacity: 'sparse',
    symmetry: 'approximate',
    balance: 'centered',
    edgeActivity: 'moderate',
  },
}, metadata, makeRadialShape(geometry));

const repeatRadial = (metadata, geometry) => createDefinition({
  family: 'emblem',
  precision: 3,
  tension: 0,
  selection: {
    uses: ['badge', 'media'],
    aspect: { min: 0.8, preferred: 1, max: 1.25 },
    contentCapacity: 'sparse',
    symmetry: 'radial',
    balance: 'centered',
    edgeActivity: 'active',
  },
}, metadata, makeRepeatingRadialShape(geometry));

const generatedFrame = (metadata, points) => createDefinition({
  family: 'frame',
  precision: 3,
  tension: 0,
  selection: {
    uses: ['card', 'panel'],
    aspect: { min: 1, preferred: 1.5, max: 2.5 },
    contentCapacity: 'dense',
    symmetry: 'bilateral',
    balance: 'centered',
    edgeActivity: 'calm',
  },
}, metadata, points);

export const definitions = [
  edge({
    id: 'golden-tide',
    name: 'Golden Tide',
    description: 'Balanced asymmetry with Fibonacci-adjacent edge rhythms and golden-ratio spacing.',
    tags: ['organic', 'golden-ratio', 'editorial', 'container'],
    recommendedFor: ['hero panels', 'empty states', 'feature callouts'],
    safeInset: 10,
    fallbackRadius: '24px',
    selection: {
      uses: ['card', 'callout', 'hero', 'panel'],
      aspect: { min: 1.15, preferred: 1.5, max: 2 },
      contentCapacity: 'dense',
    },
  }, {
    counts: { top: 3, right: 3, bottom: 5, left: 2 },
    inset: { top: 5, right: 3.2, bottom: 4.5, left: 3.6 },
    amplitude: { top: 2.1, right: 1.45, bottom: 2, left: 1.55 },
    spacingRatio: PHI,
    secondaryRatio: 1 / PHI,
    spacingPhase: { right: 1, left: 1 },
    levelPhase: { bottom: 2, left: 1 },
  }),
  edge({
    id: 'quiet-coast',
    name: 'Quiet Coast',
    description: 'A low-amplitude shoreline for calm cards that still need a handmade edge.',
    tags: ['subtle', 'calm', 'container', 'content-safe'],
    recommendedFor: ['article cards', 'quotes', 'forms'],
    safeInset: 8,
    fallbackRadius: '20px',
    selection: {
      uses: ['card', 'form', 'panel'],
      edgeActivity: 'calm',
    },
  }, {
    counts: { top: 2, right: 2, bottom: 3, left: 2 },
    inset: 4.5,
    amplitude: { top: 1.1, right: 0.85, bottom: 1.3, left: 0.9 },
    spacingRatio: 1.3,
    secondaryRatio: 0.72,
    spacingPhase: { bottom: 1 },
  }),
  edge({
    id: 'paper-drift',
    name: 'Paper Drift',
    description: 'Uneven deckled motion with enough restraint for long-form content.',
    tags: ['paper', 'editorial', 'asymmetric', 'container'],
    recommendedFor: ['essays', 'notes', 'testimonials'],
    safeInset: 9,
    fallbackRadius: '18px',
  }, {
    counts: { top: 4, right: 3, bottom: 4, left: 3 },
    inset: { top: 4.7, right: 4.2, bottom: 4.5, left: 4.1 },
    amplitude: { top: 1.45, right: 1.15, bottom: 1.6, left: 1.25 },
    spacingRatio: PHI,
    secondaryRatio: 0.57,
    spacingPhase: { top: 1, bottom: 1 },
    levelPhase: { right: 2 },
  }),
  edge({
    id: 'soft-stamp',
    name: 'Soft Stamp',
    family: 'scalloped',
    description: 'Small regular scallops with softened joins instead of sharp perforations.',
    tags: ['scalloped', 'regular', 'label', 'container'],
    recommendedFor: ['coupons', 'announcements', 'price cards'],
    safeInset: 8,
    fallbackRadius: '16px',
    selection: {
      uses: ['callout', 'coupon', 'panel'],
      contentCapacity: 'standard',
      symmetry: 'bilateral',
      edgeActivity: 'active',
    },
  }, {
    counts: { top: 6, right: 4, bottom: 6, left: 4 },
    inset: 4.3,
    amplitude: 1.1,
    spacingRatio: 1,
    secondaryRatio: 1,
  }),
  edge({
    id: 'north-wind',
    name: 'North Wind',
    family: 'asymmetric',
    description: 'A livelier top edge settles into quieter sides and a grounded base.',
    tags: ['asymmetric', 'hero', 'directional', 'container'],
    recommendedFor: ['mastheads', 'launch panels', 'section intros'],
    safeInset: 10,
    fallbackRadius: '28px',
    selection: {
      uses: ['hero', 'media', 'panel'],
      balance: 'top-heavy',
      edgeActivity: 'active',
    },
  }, {
    counts: { top: 4, right: 2, bottom: 3, left: 2 },
    inset: { top: 5.6, right: 4.2, bottom: 4.4, left: 4.5 },
    amplitude: { top: 2.6, right: 1.1, bottom: 1.35, left: 1.05 },
    spacingRatio: 1.45,
    secondaryRatio: 0.62,
    spacingPhase: { top: 1 },
  }),
  edge({
    id: 'riverbank',
    name: 'Riverbank',
    family: 'asymmetric',
    description: 'Vertical motion leads this broad, readable frame with an off-center current.',
    tags: ['flowing', 'asymmetric', 'container', 'sidebar'],
    recommendedFor: ['side panels', 'profiles', 'navigation cards'],
    safeInset: 10,
    fallbackRadius: '26px',
    selection: {
      uses: ['card', 'panel', 'sidebar'],
      aspect: { min: 0.75, preferred: 1.15, max: 1.75 },
      balance: 'right-heavy',
    },
  }, {
    counts: { top: 2, right: 3, bottom: 4, left: 3 },
    inset: { top: 4.6, right: 5.2, bottom: 4.8, left: 5 },
    amplitude: { top: 1.2, right: 2.15, bottom: 1.45, left: 1.9 },
    spacingRatio: PHI,
    secondaryRatio: 0.64,
    spacingPhase: { right: 1, bottom: 1 },
    levelPhase: { left: 2 },
  }),
  edge({
    id: 'linen',
    name: 'Linen',
    description: 'Fine texture around a nearly rectangular silhouette.',
    tags: ['subtle', 'texture', 'content-safe', 'container'],
    recommendedFor: ['documentation', 'settings', 'dense content'],
    safeInset: 7,
    fallbackRadius: '14px',
    selection: { edgeActivity: 'calm' },
  }, {
    counts: { top: 3, right: 2, bottom: 3, left: 2 },
    inset: 3.8,
    amplitude: { top: 0.85, right: 0.7, bottom: 0.95, left: 0.72 },
    spacingRatio: 1.25,
    secondaryRatio: 0.7,
    spacingPhase: { left: 1 },
  }),
  edge({
    id: 'tidepool',
    name: 'Tidepool',
    description: 'Deeper alternating pockets make a confident display container.',
    tags: ['bold', 'organic', 'display', 'container'],
    recommendedFor: ['image frames', 'campaign panels', 'event cards'],
    safeInset: 11,
    fallbackRadius: '32px',
    selection: {
      uses: ['card', 'media', 'panel'],
      contentCapacity: 'standard',
      edgeActivity: 'active',
    },
  }, {
    counts: { top: 3, right: 4, bottom: 4, left: 3 },
    inset: { top: 6, right: 5.8, bottom: 5.8, left: 5.7 },
    amplitude: { top: 2.45, right: 2.2, bottom: 2.55, left: 2.1 },
    spacingRatio: PHI,
    secondaryRatio: 0.62,
    spacingPhase: { right: 1, left: 1 },
  }),
  edge({
    id: 'longwave',
    name: 'Longwave',
    description: 'Few broad movements create a relaxed silhouette at large sizes.',
    tags: ['broad', 'minimal', 'hero', 'container'],
    recommendedFor: ['hero sections', 'full-width promos', 'large media'],
    safeInset: 12,
    fallbackRadius: '36px',
    selection: {
      uses: ['hero', 'media'],
      aspect: { min: 1.5, preferred: 2, max: 3 },
      contentCapacity: 'standard',
      edgeActivity: 'calm',
    },
  }, {
    counts: { top: 1, right: 2, bottom: 2, left: 1 },
    inset: { top: 6.3, right: 5.8, bottom: 6, left: 5.6 },
    amplitude: { top: 3.1, right: 2.5, bottom: 2.8, left: 2.65 },
    spacingRatio: PHI,
    secondaryRatio: 0.68,
    spacingPhase: { bottom: 1 },
  }),
  edge({
    id: 'meadow-frame',
    name: 'Meadow Frame',
    description: 'A breezy perimeter with a more active right edge and gentle floor.',
    tags: ['natural', 'asymmetric', 'friendly', 'container'],
    recommendedFor: ['community cards', 'onboarding', 'friendly notices'],
    safeInset: 10,
    fallbackRadius: '24px',
  }, {
    counts: { top: 2, right: 4, bottom: 3, left: 2 },
    inset: { top: 4.8, right: 5.4, bottom: 4.8, left: 4.2 },
    amplitude: { top: 1.5, right: 2, bottom: 1.4, left: 1.15 },
    spacingRatio: 1.5,
    secondaryRatio: 0.6,
    spacingPhase: { top: 1, right: 1 },
  }),
  edge({
    id: 'cloud-frame',
    name: 'Cloud Frame',
    family: 'blob',
    description: 'Generous rounded billows around a content-safe center.',
    tags: ['cloud', 'soft', 'playful', 'container'],
    recommendedFor: ['kids content', 'celebrations', 'friendly CTAs'],
    safeInset: 12,
    fallbackRadius: '40px',
    selection: {
      uses: ['callout', 'card', 'panel'],
      contentCapacity: 'standard',
      edgeActivity: 'active',
    },
  }, {
    counts: { top: 4, right: 3, bottom: 5, left: 3 },
    inset: 6.4,
    amplitude: { top: 2.8, right: 2.55, bottom: 2.9, left: 2.45 },
    spacingRatio: 1.2,
    secondaryRatio: 0.75,
    levelPhase: { bottom: 2 },
  }),
  edge({
    id: 'deckle',
    name: 'Deckle',
    family: 'scalloped',
    description: 'Many restrained irregularities suggest a torn handmade paper edge.',
    tags: ['paper', 'fine', 'editorial', 'container'],
    recommendedFor: ['captions', 'archive cards', 'print-inspired layouts'],
    safeInset: 8,
    fallbackRadius: '12px',
    selection: {
      uses: ['card', 'note', 'panel'],
      edgeActivity: 'active',
    },
  }, {
    counts: { top: 7, right: 5, bottom: 6, left: 5 },
    inset: 4,
    amplitude: { top: 0.95, right: 0.8, bottom: 1, left: 0.82 },
    spacingRatio: 1.1,
    secondaryRatio: 0.55,
    spacingPhase: { top: 1, bottom: 1 },
    levelPhase: { right: 2, left: 1 },
  }),
  radial({
    id: 'river-pebble',
    name: 'River Pebble',
    description: 'An easy oval with small irregularities and no obvious repeated lobe.',
    tags: ['radial', 'pebble', 'badge', 'media'],
    recommendedFor: ['portraits', 'logos', 'short quotes'],
    safeInset: 20,
    fallbackRadius: '50%',
  }, {
    lobes: 7,
    center: [50, 50],
    radius: [41, 35],
    amplitude: 0.075,
    secondaryRatio: 0.58,
    phase: -Math.PI / 2.15,
  }),
  radial({
    id: 'sun-coin',
    name: 'Sun Coin',
    family: 'emblem',
    description: 'A fine twelve-beat seal that reads as warm rather than spiky.',
    tags: ['radial', 'seal', 'regular', 'badge'],
    recommendedFor: ['prices', 'awards', 'small illustrations'],
    safeInset: 19,
    fallbackRadius: '50%',
    selection: {
      uses: ['badge', 'price', 'seal'],
      symmetry: 'radial',
      edgeActivity: 'active',
    },
  }, {
    lobes: 12,
    center: [50, 50],
    radius: [40, 40],
    amplitude: 0.085,
    secondaryRatio: 1,
  }),
  radial({
    id: 'coral-bloom',
    name: 'Coral Bloom',
    family: 'emblem',
    description: 'An eight-lobed display shape with alternating primary and secondary petals.',
    tags: ['radial', 'bold', 'flower', 'badge'],
    recommendedFor: ['stickers', 'campaign marks', 'illustrations'],
    safeInset: 22,
    fallbackRadius: '45%',
    selection: {
      uses: ['badge', 'illustration', 'sticker'],
      contentCapacity: 'decorative',
      symmetry: 'radial',
      edgeActivity: 'active',
    },
  }, {
    lobes: 8,
    center: [50, 50],
    radius: [39, 39],
    amplitude: 0.14,
    secondaryRatio: 0.62,
    phase: -Math.PI / 2.08,
  }),
  radial({
    id: 'petal-seal',
    name: 'Petal Seal',
    family: 'emblem',
    description: 'Six broad petals form a soft emblem with a generous center.',
    tags: ['radial', 'flower', 'soft', 'badge'],
    recommendedFor: ['testimonials', 'avatars', 'certification marks'],
    safeInset: 23,
    fallbackRadius: '45%',
    selection: {
      uses: ['avatar', 'badge', 'seal'],
      symmetry: 'radial',
    },
  }, {
    lobes: 6,
    center: [50, 50],
    radius: [39, 39],
    amplitude: 0.13,
    secondaryRatio: 0.72,
  }),
  radial({
    id: 'ink-drop',
    name: 'Ink Drop',
    description: 'A slightly off-center darkroom blob with restrained surface movement.',
    tags: ['radial', 'asymmetric', 'blob', 'media'],
    recommendedFor: ['photography', 'portraits', 'ambient decoration'],
    safeInset: 20,
    fallbackRadius: '48%',
    selection: {
      uses: ['avatar', 'decoration', 'media'],
      contentCapacity: 'decorative',
      balance: 'bottom-heavy',
    },
  }, {
    lobes: 9,
    center: [49, 51],
    radius: [40, 36],
    amplitude: 0.09,
    secondaryRatio: 0.52,
    phase: -Math.PI / 1.95,
  }),
  radial({
    id: 'halo-five',
    name: 'Halo Five',
    description: 'Five slow lobes create a friendly mark that remains visually centered.',
    tags: ['radial', 'minimal', 'blob', 'badge'],
    recommendedFor: ['icons', 'numbers', 'compact calls to action'],
    safeInset: 22,
    fallbackRadius: '46%',
    selection: {
      uses: ['badge', 'callout', 'icon'],
      symmetry: 'radial',
    },
  }, {
    lobes: 5,
    center: [50, 50],
    radius: [39, 39],
    amplitude: 0.105,
    secondaryRatio: 0.66,
    phase: -Math.PI / 2.1,
  }),
  generatedFrame({
    id: 'fillet-frame',
    name: 'Fillet Frame',
    description: 'A near-rectangular frame with explicit, even corner fillets for a calm silhouette.',
    tags: ['fillet', 'rounded', 'content-safe', 'container'],
    recommendedFor: ['article cards', 'documentation', 'forms'],
    safeInset: 10,
    fallbackRadius: '22px',
    selection: {
      uses: ['card', 'form', 'panel'],
      aspect: { min: 1.1, preferred: 1.5, max: 2.25 },
    },
  }, filletPoints([
    [4, 5],
    [96, 5],
    [96, 95],
    [4, 95],
  ], { radius: 0.2 })),
  generatedFrame({
    id: 'squircle',
    name: 'Squircle',
    description: 'A responsive superellipse that keeps a rectangular feel while softening every corner.',
    tags: ['superellipse', 'squircle', 'rounded', 'container'],
    recommendedFor: ['app shells', 'cards', 'navigation panels'],
    safeInset: 12,
    fallbackRadius: '28px',
    selection: {
      uses: ['card', 'panel', 'shell'],
      aspect: { min: 0.9, preferred: 1.25, max: 2 },
      symmetry: 'bilateral',
      edgeActivity: 'calm',
    },
  }, makeSuperellipseShape({ exponent: 4, radius: [43, 42], points: 32 })),
  generatedFrame({
    id: 'soft-superellipse',
    name: 'Soft Superellipse',
    description: 'A lower-exponent superellipse that sits between an ellipse and a squircle.',
    tags: ['superellipse', 'soft', 'responsive', 'container'],
    recommendedFor: ['media frames', 'profile cards', 'feature panels'],
    safeInset: 13,
    fallbackRadius: '34px',
    selection: {
      uses: ['card', 'media', 'panel'],
      aspect: { min: 0.85, preferred: 1.4, max: 2.25 },
      symmetry: 'bilateral',
    },
  }, makeSuperellipseShape({ exponent: 3, center: [50, 50], radius: [44, 40], points: 28 })),
  repeatEdge({
    id: 'repeat-wave',
    name: 'Repeat Wave',
    family: 'scalloped',
    description: 'A balanced repeating edge pattern with the same number of beats on every side.',
    tags: ['repeating', 'scalloped', 'balanced', 'container'],
    recommendedFor: ['announcement cards', 'banners', 'event panels'],
    safeInset: 10,
    fallbackRadius: '24px',
    selection: {
      uses: ['banner', 'callout', 'panel'],
      contentCapacity: 'standard',
      symmetry: 'bilateral',
      edgeActivity: 'active',
    },
  }, {
    repeats: 5,
    inset: 5,
    amplitude: 1.35,
    spacingRatio: PHI,
    secondaryRatio: 0.62,
    spacingPhase: { top: 1, bottom: 1 },
  }),
  repeatRadial({
    id: 'repeat-seal',
    name: 'Repeat Seal',
    description: 'A deterministic radial repeat helper for badges that need a measured, even rhythm.',
    tags: ['repeating', 'radial', 'seal', 'badge'],
    recommendedFor: ['badges', 'stamps', 'small illustrations'],
    safeInset: 22,
    fallbackRadius: '48%',
    selection: {
      uses: ['badge', 'seal', 'sticker'],
      contentCapacity: 'decorative',
    },
  }, {
    repeats: 10,
    center: [50, 50],
    radius: [39, 39],
    amplitude: 0.1,
    secondaryRatio: 0.72,
  }),
];

export function getDefinition(id) {
  return definitions.find((definition) => definition.id === id) ?? null;
}
